"""FelLaw improvement backlog — driven by metrics, not guesswork.

Each item: metric, evidence, acceptance, size, risk, status. The loop driver
picks the top READY item whose budget fits. Nothing is DONE without a measured
delta and an archived metrics report.

Budget rule: <=3 files changed, <=45 min, all gates green, metrics must not
regress; otherwise REVERT and mark the item BLOCKED with the measured reason.
"""

items = [
    {"id": "R1", "title": "Semantic embeddings for law corpus (vector path)", "metric": "retrieval.recall_at_5 >= 0.95, mrr >= 0.75", "evidence": "metrics 20260906T2031: 14/15; last miss 'Miete mindern' needs §536 semantics; lexical coverage cannot rank it above §556", "acceptance": "install multilingual embedding model via Ollama (e.g. bge-m3 / nomic-embed-text) OR approved API key; backfill embeddings; vector path returns mode='vector'; golden set 15/15", "size": "M", "risk": "vector column is fixed 1536-dim; bge-m3 outputs 1024-dim → needs migration to variable-dim or dimension match; Ollama RAM limit 12.7GiB observed", "status": "DONE (2026-09-07: user approved KIT-hosted embedding model; EMBEDDING_PROVIDER decoupled from AI_PROVIDER so chat stays local Ollama; kit.qwen3-embedding-8b via KIT Toolbox (4096-dim, OpenAI-compatible, key from env KIT_API_KEY); migration 007 vector 1536→4096 (no ANN index: pgvector hnsw caps 2000/halfvec 4000 and KIT endpoint rejects dimensions param; seq cosine scan correct at 33 rows); 33 statutes backfilled via create_embeddings_batch; measured vector-mode recall@5 0.95→1.0, mrr 0.7167→0.7917, all 20 golden queries mode=vector; chat metrics intact 1.0/1.0/1.0; gates green)"},
    {"id": "R2", "title": "Expand supported-notice golden set (not the whole law corpus)", "metric": "supported-notice classification, fact, deadline, abstention, provenance, and next-action gates", "evidence": "PR-00 product contract (2026-09-09): broad corpus expansion reinforces the rejected super-app thesis; current retrieval metrics remain secondary until the first-response core is measurable", "acceptance": "build professionally reviewed examples for employment termination, traffic penalty, authority/residence notices, and unsupported ambiguity; record trigger facts, expected deadlines, required next action, provenance, and expected abstention; do not seed unrelated law domains", "size": "M", "risk": "legal review and privacy handling required; no deadline rule is added without counsel-reviewed source/version", "status": "BLOCKED (2026-09-09: product pivot freeze; replace with supported-notice evaluation plan after PR-00 through PR-04 and counsel-approved rule boundary)"},
    {"id": "R3", "title": "Section-aware query boost when user names a law", "metric": "retrieval.mrr on queries naming a section", "evidence": "closed 2026-09-06: golden set 15→20; recall@5 0.933→0.95, mrr 0.6556→0.7167; all explicit queries rank the named statute #1; gates green", "acceptance": "add golden queries with explicit sections; measure rank-1 rate", "size": "S", "risk": "low", "status": "DONE (measured delta archived: recall 0.95, mrr 0.7167)"},
    {"id": "C1", "title": "Grounded answer generation with gemma4:e2b via Ollama", "metric": "chat.citation_rate = 1.0, grounding_rate >= 0.8", "evidence": "closed 2026-09-07: local Ollama, /v1 fix, deterministic RDG disclaimer, live bot ask-path; final citation/grounding/disclaimer 1.0", "acceptance": "bot/turn ask-path composes statutes into prompt, calls local chat model, answer cites retrieved docs; disclaimer always present", "size": "M", "risk": "hallucination mitigated by prompt-with-context + citation verification", "status": "DONE (final: citation 1.0, grounding 1.0, disclaimer 1.0 deterministic; unit 22 + integration 10 green)"},
    {"id": "U1", "title": "S2 intake submission handoff (real create-case call)", "metric": "integration test: intake → POST /cases → dashboard shows case", "evidence": "S2 marked 'partial (submission handoff)' — draft persists locally but never submits", "acceptance": "authenticated intake submits via /api/v1/cases; dashboard reflects it; empty/error/loading states honest", "size": "M", "risk": "low; API contract already verified by test_case_create_and_overview_roundtrip", "status": "DONE (2026-09-07: real authenticated create-case client wired from /new-case; tsc/build green; close measured recall 0.95, MRR 0.7167; backend gates 22 unit + 10 integration green)"},
    {"id": "U2", "title": "S7 privacy flow: pre-submission privacy note component", "metric": "user-test scenario pass; a11y focus check", "evidence": "closed 2026-09-06: bilingual pre-submission privacy note rendered above submit on /new-case; honest dev backend/access/deletion copy", "acceptance": "privacy note shown before continue action on intake/upload surfaces; states who can access and where data goes", "size": "S", "risk": "low", "status": "DONE (measured delta archived: metrics flat, gates green)"},
    {"id": "U3", "title": "First-72h roadmap on dashboard (differentiator vs advocado)", "metric": "dashboard shows per-case next steps from roadmap_steps when present; no fabricated steps", "evidence": "roadmap_steps model exists and roadmap service exists; unblocked 2026-09-07 — the earlier pydantic_core gate failure was transient and is resolved (unit 22/22 + integration 10/10 green in every run since; original block reason kept for audit: pre-gates failed twice before implementation on the broken venv)", "acceptance": "cases with roadmap_steps render status; others show explicit 'roadmap not yet generated'; never invent deadlines", "size": "M", "risk": "roadmap generation depends on AI provider — display must be read-only-honest", "status": "DONE (2026-09-07: overview CaseSummary extended with roadmap_generated + next_step_title derived read-only from persisted roadmap_steps; dashboard case rows render next open step / all-completed / explicit not-generated state, never fabricated; live verify: real AI roadmap via Ollama then overview reflects it, second case shows not-generated; unit 26 + integration 10 + contract 11 + tsc + build green; close delta recall 0.95 mrr 0.7167 flat)"},
    {"id": "U4", "title": "Bilingual toggle visibility (international persona)", "metric": "DE/EN switch reachable from every top-level route", "evidence": "closed 2026-09-07: EN prompt, language schema/query/UI flow; toggle on shell with localStorage persistence", "acceptance": "language toggle on shell; stores preference; assistant and bot replies honor it", "size": "S", "risk": "low", "status": "DONE (measured delta archived: metrics flat, gates green)"},
    {"id": "T1", "title": "Convert remaining mock-style tests to real-contract tests", "metric": "no test asserts only file existence or module import without behavior", "evidence": "closed 2026-09-07: audit found all 31 tests assert observable behavior", "acceptance": "audit each test file; every test asserts observable behavior", "size": "S", "risk": "low", "status": "DONE (audit-only close: premise already satisfied, no code change)"},
    {"id": "T2", "title": "Frontend contract tests for assistant parity", "metric": "assistant surfaces verified against /platform/capabilities truth", "evidence": "cross-surface-product-validation skill; assistant must not advertise missing capabilities", "acceptance": "component renders only registry-backed capabilities; test with real registry fixture", "size": "M", "risk": "low", "status": "DONE (2026-09-07: vitest+RTL stack installed (vite-5-compatible vitest@2); 11 contract tests green vs real anonymous registry fixture snapshotted from backend truth; fixture verified field-identical to live endpoint; tsc/build green; close delta recall 0.95 mrr 0.7167 flat)"},
    {"id": "O1", "title": "Rotate dev DB credentials (user said they will rotate)", "metric": "n/a (security)", "evidence": "user will rotate FELLAW_DB_PASSWORD after dev", "acceptance": "user rotates; update .env only; never commit", "size": "S", "risk": "none after rotation", "status": "WAITING-ON-USER"},
    {"id": "O2", "title": "Telegram gateway: bind openclaw telegram channel to /platform/bot/turn", "metric": "real Telegram message → bot turn → reply (e2e)", "evidence": "endpoint live + 4 bot tests green; token remains environment placeholder", "acceptance": "gateway maps Telegram update → bot turn → reply; DM routing honored; token from env", "size": "M", "risk": "needs TELEGRAM_BOT_TOKEN value from user", "status": "DONE (2026-09-07: user-supplied @fellaw_bot token verified live via getMe (id 8644884425), stored env-managed in fellaw/.env as TELEGRAM_BOT_TOKEN, git-ignored, never committed; openclaw gateway runs on 18790 with telegram provider long-polling @fellaw_bot (proven: concurrent getUpdates → 409 conflict from gateway's own poll); agent model chain pruned to policy (KIT local aliases + kit.glm-5.3 + Ollama; removed keyless model-router/openrouter/nvidia providers that fatally blocked startup, removed excluded KIT fable); fellaw-platform skill patched: ask-intents MUST call POST /platform/bot/turn (anonymous-safe grounded statute search + citations + RDG disclaimer) instead of answering from model memory; verified live: agent loads skill, calls bot/turn with correct payload, renders grounded reply for mapped identity and honest login-link for unmapped; backend log shows real bot.turn.ask_grounded docs=5; close gates green, delta flat)"}
]
